name: devsoc_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.1
  photo_view: ^0.9.1
  font_awesome_flutter: ^8.5.0
  qr_flutter: ^3.1.0
  provider: ^4.0.3
  http: ^0.12.0+4
  shared_preferences: ^0.5.3+1
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  video_player: ^0.10.7
  url_launcher: ^5.4.1
  firebase_database: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/icons/
    - assets/img/board/
    - assets/img/others/

  fonts:
    - family: SFProTextSemibold
      fonts:
        - asset: assets/fonts/sf_pro_text_semibold.ttf
    - family: SFProDisplayMed
      fonts:
        - asset: assets/fonts/sf_pro_display_med.ttf
    - family: SFProDisplayLight
      fonts:
        - asset: assets/fonts/sf_pro_text_light.ttf
    - family: SFProDisplayReg
      fonts:
        - asset: assets/fonts/sf_pro_display_reg.ttf
